'use client';

/**
 * INPUT → AGENT → OUTPUT, drawn as one line across the hero.
 *
 * A black ribbon enters from off-screen left carrying what the customer
 * actually said, runs into the voice pill, and a mirrored ribbon leaves to
 * the right carrying the resolved order. The pill is the agent.
 *
 * The two ribbons are exact mirrors about PILL_CX, so the composition is
 * symmetric. The left one is drawn OUTSIDE-IN (from -400 toward the pill)
 * rather than as a literal mirror of the right path: a mirrored path would
 * run right-to-left and render its text backwards.
 *
 * Everything shares one coordinate space, DESIGN_W x DESIGN_H. The SVG
 * scales with preserveAspectRatio xMidYMid and the pill is placed as a
 * PERCENTAGE of the same box, so the junctions hold at any width rather
 * than drifting apart.
 */

export const DESIGN_W = 1152; // max-w-6xl content width
export const DESIGN_H = 736;

/** Where both ribbons meet the pill. */
const JUNCTION_Y = 624;
const PILL_CX = 576;
const PILL_HALF = 142;

/** what the customer said */
const RAW =
  'bhaiya wo peela wala tel aur do kilo ashirwaad ata bhej dena  ·  haan chai patti bhi  ·  ';

/**
 * What comes OUT of the agent: the steps it actually ran, in order.
 * These are the real pipeline stages, not decoration, so the ribbon doubles
 * as a plain-English description of what the thing does.
 */
const RESOLVED =
  '·  Inventory checked   ·  Substitute chosen   ·  Order created   ' +
  '·  Payment link generated   ·  Bill sent on WhatsApp   ';

const STROKE = 42;
/** nudge the text baseline down so it sits centred inside the band */
const BASELINE = 7;

export function HeroFlow() {
  const lx = PILL_CX - PILL_HALF - 6;
  const rx = PILL_CX + PILL_HALF + 6;

  return (
    <svg
      aria-hidden
      viewBox={`0 0 ${DESIGN_W} ${DESIGN_H}`}
      preserveAspectRatio="xMidYMid meet"
      className="pointer-events-none absolute inset-0 hidden h-full w-full overflow-visible select-none lg:block"
    >
      {/* ---------- LEFT: what was said, arriving from off-screen ---------- */}
      <path
        fill="none"
        stroke="var(--ink)"
        strokeWidth={STROKE}
        strokeLinecap="butt"
        d={`M -400 438 C 80 578, 300 612, ${lx} ${JUNCTION_Y - 4}`}
      />
      <path
        id="raw-baseline"
        fill="none"
        d={`M -400 ${438 + BASELINE} C 80 ${578 + BASELINE}, 300 ${612 + BASELINE}, ${lx} ${JUNCTION_Y - 4 + BASELINE}`}
      />
      <text
        className="fill-[var(--bg)]"
        style={{ fontSize: 16, fontWeight: 600, letterSpacing: '0.01em' }}
      >
        {/* three copies drifting -1/3: drift must equal 1/copies or the band
            goes bare partway through each cycle */}
        <textPath href="#raw-baseline" startOffset="0%">
          {RAW}
          {RAW}
          {RAW}
          <animate
            attributeName="startOffset"
            from="-33.333%"
            to="0%"
            dur="30s"
            repeatCount="indefinite"
          />
        </textPath>
      </text>

      {/* ---------- RIGHT: the resolved order, leaving ----------
          The band starts EMPTY and grows outward from the pill, so the
          output reads as being generated by the agent rather than having
          always been there. A clip rect anchored at the pill's right edge
          widens once and freezes; the band and its text are both inside it,
          so they appear together as it opens. */}
      <defs>
        <clipPath id="reveal-right">
          <rect x={rx} y="0" width="0" height={DESIGN_H}>
            <animate
              attributeName="width"
              values="0;1000"
              keyTimes="0;1"
              calcMode="spline"
              keySplines="0.22 1 0.36 1"
              dur="2.4s"
              begin="0.7s"
              fill="freeze"
            />
          </rect>
        </clipPath>
      </defs>

      <g clipPath="url(#reveal-right)">
      <path
        fill="none"
        stroke="var(--ink)"
        strokeWidth={STROKE}
        strokeLinecap="butt"
        d={`M ${rx} ${JUNCTION_Y - 4} C 852 612, 1072 578, 1552 438`}
      />
      <path
        id="resolved-baseline"
        fill="none"
        d={`M ${rx} ${JUNCTION_Y - 4 + BASELINE} C 852 ${612 + BASELINE}, 1072 ${578 + BASELINE}, 1552 ${438 + BASELINE}`}
      />
      <text
        className="fill-[var(--bg)]"
        style={{ fontSize: 16, fontWeight: 600, letterSpacing: '0.01em' }}
      >
        {/* Same direction values as the left band, and deliberately so.
            startOffset INCREASING moves text forward along its own path.
            The left path runs off-screen -> pill, so forward reads as
            arriving. The right path runs pill -> off-screen, so the same
            forward motion reads as leaving. Flipping the sign here made
            the output crawl back INTO the agent. */}
        <textPath href="#resolved-baseline" startOffset="0%">
          {RESOLVED}
          {RESOLVED}
          {RESOLVED}
          <animate
            attributeName="startOffset"
            from="-33.333%"
            to="0%"
            dur="30s"
            repeatCount="indefinite"
          />
        </textPath>
      </text>
      </g>
    </svg>
  );
}

/**
 * The agent. Sits on the junction both ribbons meet, with a label above it
 * so the diagram reads without explanation: said → processed → resolved.
 *
 * Bars come from a fixed array rather than Math.random so server and client
 * render identically and hydration stays quiet.
 */
const BARS = [
  6, 11, 18, 9, 22, 30, 16, 24, 12, 7, 15, 26, 34, 20, 11, 8, 14, 28, 36, 22,
  13, 9, 19, 31, 17, 10, 23, 15, 8, 12,
];

export function VoicePill({ pinned = false }: { pinned?: boolean }) {
  const label = (
    <div className="mb-3 flex items-center justify-center gap-2 whitespace-nowrap">
      <span className="breathe inline-block h-1.5 w-1.5 rounded-full bg-[var(--hot)]" />
      <span className="eyebrow">AI agent processing</span>
    </div>
  );

  const pill = (
    <div className="flex w-fit items-center gap-3 rounded-[28px] border border-[var(--ink)] bg-[var(--bg)] px-5 py-3.5">
      <span className="flex h-10 items-center gap-[3px]">
        {BARS.map((h, i) => (
          <span
            key={i}
            className="wave-bar w-[3px] rounded-full bg-[var(--ink)]"
            style={{ height: h, animationDelay: `${i * 55}ms` }}
          />
        ))}
      </span>
      <span className="ml-1 h-1.5 w-10 rounded-full bg-[var(--ink)]/25" />
    </div>
  );

  if (!pinned) {
    return (
      <div className="mx-auto w-fit">
        {label}
        {pill}
      </div>
    );
  }

  return (
    <div
      className="absolute z-10 hidden -translate-x-1/2 -translate-y-1/2 lg:block"
      style={{
        left: `${(PILL_CX / DESIGN_W) * 100}%`,
        top: `${(JUNCTION_Y / DESIGN_H) * 100}%`,
      }}
    >
      {/* label floats above the pill without shifting it off the junction */}
      <div className="absolute inset-x-0 bottom-full mb-3">
        {label}
      </div>
      {pill}
    </div>
  );
}
